name: Deploy via FTP to Hostinger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install Dependencies
      run: |
        cd frontend
        npm ci

    - name: Build Project
      run: |
        cd frontend
        npm run build

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy files via SFTP (rsync)
      run: |
        sshpass -p "${{ secrets.FTP_PASSWORD }}" rsync -avz -e "ssh -p 65002 -o StrictHostKeyChecking=no" ./frontend/dist/ ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }}:/domains/tucatalogoideal.com/public_html/
